In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Superstore.csv',encoding='unicode_escape')

In [4]:
df

,Order ID,Order Line ID,Order Date,Ship Date,Ship Mode,Order Priority,Customer ID,Customer Name,Customer Email,Gender,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,CA-2016-152156-1,11/8/2016,11/11/2016,Second Class,Medium,CG-12520,Claire Gute,claire.gute@hotmail.com,F,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,CA-2016-152156-2,11/8/2016,11/11/2016,Second Class,Low,CG-12520,Claire Gute,claire.gute@hotmail.com,F,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,CA-2016-138688-1,6/12/2016,6/16/2016,Second Class,Critical,DV-13045,Darrin Van Huff,darrin.huff@hotmail.com,M,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,US-2015-108966-1,10/11/2015,10/18/2015,Standard Class,Low,SO-20335,Sean O'Donnell,sean.o'donnell@hotmail.com,M,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,US-2015-108966-2,10/11/2015,10/18/2015,Standard Class,Low,SO-20335,Sean O'Donnell,sean.o'donnell@hotmail.com,M,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,CA-2014-110422-1,1/21/2014,1/23/2014,Second Class,Critical,TB-21400,Tom Boeckenhauer,tom.boeckenhauer@hotmail.com,M,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,CA-2017-121258-1,2/26/2017,3/3/2017,Standard Class,Not Specified,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,CA-2017-121258-2,2/26/2017,3/3/2017,Standard Class,Critical,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,CA-2017-121258-3,2/26/2017,3/3/2017,Standard Class,Critical,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2017-119914,CA-2017-119914-1,5/4/2017,5/9/2017,Second Class,Medium,CC-12220,Chris Cortes,chris.cortes@hotmail.com,M,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [5]:
df.head(4)

,Order ID,Order Line ID,Order Date,Ship Date,Ship Mode,Order Priority,Customer ID,Customer Name,Customer Email,Gender,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,CA-2016-152156-1,11/8/2016,11/11/2016,Second Class,Medium,CG-12520,Claire Gute,claire.gute@hotmail.com,F,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,CA-2016-152156-2,11/8/2016,11/11/2016,Second Class,Low,CG-12520,Claire Gute,claire.gute@hotmail.com,F,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,CA-2016-138688-1,6/12/2016,6/16/2016,Second Class,Critical,DV-13045,Darrin Van Huff,darrin.huff@hotmail.com,M,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,US-2015-108966-1,10/11/2015,10/18/2015,Standard Class,Low,SO-20335,Sean O'Donnell,sean.o'donnell@hotmail.com,M,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310

In [6]:
df.tail(5)

,Order ID,Order Line ID,Order Date,Ship Date,Ship Mode,Order Priority,Customer ID,Customer Name,Customer Email,Gender,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,CA-2014-110422,CA-2014-110422-1,1/21/2014,1/23/2014,Second Class,Critical,TB-21400,Tom Boeckenhauer,tom.boeckenhauer@hotmail.com,M,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,CA-2017-121258,CA-2017-121258-1,2/26/2017,3/3/2017,Standard Class,Not Specified,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,CA-2017-121258,CA-2017-121258-2,2/26/2017,3/3/2017,Standard Class,Critical,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,CA-2017-121258,CA-2017-121258-3,2/26/2017,3/3/2017,Standard Class,Critical,DB-13060,Dave Brooks,dave.brooks@hotmail.com,M,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,CA-2017-119914,CA-2017-119914-1,5/4/2017,5/9/2017,Second Class,Medium,CC-12220,Chris Cortes,chris.cortes@hotmail.com,M,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [7]:
df.tail(1)

,Order ID,Order Line ID,Order Date,Ship Date,Ship Mode,Order Priority,Customer ID,Customer Name,Customer Email,Gender,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9993,CA-2017-119914,CA-2017-119914-1,5/4/2017,5/9/2017,Second Class,Medium,CC-12220,Chris Cortes,chris.cortes@hotmail.com,M,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [8]:
df.columns

Index(['Order ID', 'Order Line ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Order Priority', 'Customer ID', 'Customer Name', 'Customer Email',
       'Gender', 'Birth Date', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [10]:
df["Order ID"]

0       CA-2016-152156
1       CA-2016-152156
2       CA-2016-138688
3       US-2015-108966
4       US-2015-108966
             ...
9989    CA-2014-110422
9990    CA-2017-121258
9991    CA-2017-121258
9992    CA-2017-121258
9993    CA-2017-119914
Name: Order ID, Length: 9994, dtype: object

In [15]:
df.head(5)[['Customer Name','Customer Email','Profit']]

     Customer Name              Customer Email    Profit
0      Claire Gute     claire.gute@hotmail.com   41.9136
1      Claire Gute     claire.gute@hotmail.com  219.5820
2  Darrin Van Huff     darrin.huff@hotmail.com    6.8714
3   Sean O'Donnell  sean.o'donnell@hotmail.com -383.0310
4   Sean O'Donnell  sean.o'donnell@hotmail.com    2.5164

In [16]:
df.shape

(9994, 25)

In [17]:
df.ndim

2

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9994 non-null   object
 1   Order Line ID   9994 non-null   object
 2   Order Date      9994 non-null   datetime64[ns]
 3   Ship Date       9994 non-null   datetime64[ns]
 4   Ship Mode       9994 non-null   object
 5   Order Priority  9994 non-null   object
 6   Customer ID     9994 non-null   object
 7   Customer Name   9994 non-null   object
 8   Customer Email  9994 non-null   object
 9   Gender          9994 non-null   object
 10  Birth Date      9994 non-null   datetime64[ns]
 11  Segment         9994 non-null   object
 12  Country         9994 non-null   object
 13  City            9994 non-null   object
 14  State           9994 non-null   object
 15  Postal Code     9994 non-null   int64
 16  Region          9994 non-null   object
 17  Product ID      9994 non-null   object
 18  Category        9994 non-null   object
 19  Sub-Category    9994 non-null   object
 20  Product Name    9994 non-null   object
 21  Sales           9994 non-null   float64
 22  Quantity        9994 non-null   int32
 23  Discount        9994 non-null   float64
 24  Profit          9994 non-null   float64
dtypes: datetime64[ns](3), float64(3), int32(1), int64(1), object(17)
memory usage: 1.9+ MB

In [21]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [23]:
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [25]:
df['Birth Date'] = pd.to_datetime(df['Birth Date'])

In [27]:
df['Quantity'] = df['Quantity'].astype(int)